### ISSUE TITLE
Make login use cookies instead of a single server-side variable

### ISSUE THREAD

**Issue by jacob-g** [qkennedy/RentConnect#43]

**Comment by qkennedy** [comment]
We should think about using this: [](https://www.npmjs.com/package/vue-session) it has a very simple login flow, we would need the backend to start creating some kind of token, and verifying that token in the session when more requests get sent.  We could also use this to store basic user details on the frontend.

**Comment by qkennedy** [comment]
I'll just do this

**Comment by qkennedy** [comment]
Okay, so, the new way you can find what user you are is in the link above, I stored it as userId in the session, so you should be able to get the user (if they are logged in) with something like `this.$session.get('userId')`  I also stored their role for basic page permissions, which you can get in a similar way.
Tell me if you have any questions related to this
