### ISSUE TITLE
MaintRequestFactory::addCommentForRequest broken

### ISSUE THREAD

**Issue by jacob-g** [qkennedy/RentConnect#48]
For whatever reason, the code seems to be running a SELECT query rather than an INSERT query.

The commit that changed this is at https://github.com/qkennedy/RentConnect/commit/d17ce44b3900f8b683a86d92a9a5283ff1753890#r28625559

**Comment by jacob-g** [comment]
Also, the function currently only takes requestId as an argument:
`getCommentsByRequestId: function(requestId) {`
while it is passed:
`maintRequestFactory.addCommentForRequest(req.params.id, req.body).then(`
The second argument in the function should be added called "comment".

**Comment by qkennedy** [comment]
this should be fixed, just add the userId from the session into the body as 'creatorId' when you send the post
